"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { factionName, isNight, roleName, ROLES, type GameActionType, type GameView, type Player, type Role } from "@/lib/game";

type Session = { playerId: string; isHost: boolean };
type Submit = (type: GameActionType, extra?: { targetId?: string; targetIds?: string[]; use?: boolean }) => Promise<void>;
const roleIcon: Record<Role, string> = { WOLF: "☾", VILLAGER: "✦", SEER: "◉", GUARD: "◈", FOOL: "♙", CURSED: "☠", WITCH: "⚗", CUPID: "♡" };
const roleTone: Record<Role, string> = { WOLF: "text-red-200 bg-red-400/10 border-red-300/20", VILLAGER: "text-emerald-100 bg-emerald-300/10 border-emerald-200/15", SEER: "text-sky-100 bg-sky-300/10 border-sky-200/15", GUARD: "text-cyan-100 bg-cyan-300/10 border-cyan-200/15", FOOL: "role-fool", CURSED: "text-violet-100 bg-violet-300/10 border-violet-200/15", WITCH: "text-fuchsia-100 bg-fuchsia-300/10 border-fuchsia-200/15", CUPID: "text-pink-100 bg-pink-300/10 border-pink-200/15" };

function readSession(gameId: string): Session | null { const raw = localStorage.getItem(`werewolf:${gameId}`); if (!raw) return null; try { return JSON.parse(raw) as Session; } catch { return null; } }
function phaseCopy(phase: string) {
  const copy: Record<string, { eyebrow: string; title: string; note: string; icon: string }> = {
    LOBBY: { eyebrow: "Phòng chờ", title: "Ngôi làng đang tụ họp", note: "Chủ phòng sẽ bắt đầu khi mọi người đã sẵn sàng.", icon: "☾" },
    FINISHED: { eyebrow: "Kết quả", title: "Màn đêm đã khép lại", note: "Các vai trò cuối ván đã được công bố.", icon: "✦" },
    NIGHT_CUPID: { eyebrow: "Đêm đầu tiên", title: "Cupid đang ghép đôi", note: "Cả làng chờ một sợi dây tình yêu được buộc lại.", icon: "♡" },
    NIGHT_GUARD: { eyebrow: "Đêm", title: "Bảo vệ đang hành động", note: "Những cánh cửa trong làng đang được canh giữ.", icon: "◈" },
    NIGHT_WOLF: { eyebrow: "Đêm", title: "Bầy Sói đang lựa chọn", note: "Mọi người hãy chờ cho tới khi màn đêm đi qua.", icon: "☾" },
    NIGHT_SEER: { eyebrow: "Đêm", title: "Tiên tri đang soi", note: "Một bí mật đang được vén lên trong bóng tối.", icon: "◉" },
    NIGHT_WITCH_HEAL: { eyebrow: "Đêm", title: "Phù thủy đang hành động", note: "Ánh lửa trong căn lều nhỏ vẫn chưa tắt.", icon: "⚗" },
    NIGHT_WITCH_POISON: { eyebrow: "Đêm", title: "Phù thủy đang hành động", note: "Ánh lửa trong căn lều nhỏ vẫn chưa tắt.", icon: "⚗" },
    DAY_NOMINATION: { eyebrow: "Ban ngày", title: "Chọn người lên giàn", note: "Mỗi người còn sống chọn một người khác.", icon: "☀" },
    DAY_DEFENSE: { eyebrow: "Ban ngày", title: "Thời gian biện hộ", note: "Hãy lắng nghe lời biện hộ trước khi quyết định.", icon: "☀" },
    DAY_EXECUTION: { eyebrow: "Ban ngày", title: "Quyết định treo cổ", note: "Lựa chọn của bạn sẽ được ghi nhận một lần.", icon: "☀" },
  };
  return copy[phase] ?? { eyebrow: isNight(phase) ? "Đêm" : "Ban ngày", title: "Ngôi làng đang chờ", note: "Hãy chờ lượt tiếp theo.", icon: "✦" };
}
function personName(players: Player[], id?: string) { return players.find((player) => player.id === id)?.name ?? "—"; }

export default function GamePage() {
  const { gameId } = useParams<{ gameId: string }>();
  const [session, setSession] = useState<Session | null>(null); const [sessionReady, setSessionReady] = useState(false); const [view, setView] = useState<GameView | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [acting, setActing] = useState(false); const [targetId, setTargetId] = useState(""); const [secondTargetId, setSecondTargetId] = useState(""); const [configuredRoles, setConfiguredRoles] = useState<Role[] | null>(null);
  const refresh = useCallback(async (activeSession: Session) => { try { setView(await api.viewGame(gameId, activeSession.playerId)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể tải ván chơi."); } finally { setLoading(false); } }, [gameId]);
  useEffect(() => { const timer = window.setTimeout(() => { setSession(readSession(gameId)); setSessionReady(true); }, 0); return () => window.clearTimeout(timer); }, [gameId]);
  useEffect(() => { if (!session) return; const initial = window.setTimeout(() => void refresh(session), 0); const timer = window.setInterval(() => void refresh(session), 3500); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [refresh, session]);
  const players = useMemo(() => view?.game.players ?? [], [view]); const alivePlayers = players.filter((player) => player.alive);
  async function submit(type: GameActionType, extra: { targetId?: string; targetIds?: string[]; use?: boolean } = {}) { if (!session) return; setActing(true); setError(""); try { setView(await api.action(gameId, session.playerId, { type, ...extra })); setTargetId(""); setSecondTargetId(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể ghi nhận lựa chọn."); } finally { setActing(false); } }
  async function start() { if (!session) return; setActing(true); setError(""); try { setView(await api.startGame(gameId, session.playerId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể bắt đầu ván."); } finally { setActing(false); } }
  async function saveRoleConfiguration(roles: Role[]) { if (!session) return; setActing(true); setError(""); try { setView(await api.configureRoles(gameId, session.playerId, roles)); setConfiguredRoles(roles); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể lưu cấu hình role."); } finally { setActing(false); } }
  if (!sessionReady) return <FullscreenMessage label="Đang xác thực người chơi…" />;
  if (!session) return <FullscreenMessage label="Không tìm thấy danh tính người chơi" detail="Hãy vào phòng từ trang chủ trên chính trình duyệt này." />;
  if (loading) return <FullscreenMessage label="Đang mở cánh cổng ngôi làng…" />;
  if (!view) return <FullscreenMessage label={error || "Không tìm thấy ván chơi."} />;

  const { game, private: privateView } = view; const self = players.find((player) => player.id === privateView.playerId); const canAct = (self?.alive || session.isHost) && game.phase !== "FINISHED"; const roleSlots = configuredRoles ?? privateView.configuredRoles ?? Array.from({ length: players.length }, () => "VILLAGER" as Role); const configurationSaved = privateView.configuredRoles?.length === players.length && privateView.configuredRoles.every((role, index) => role === roleSlots[index]); const phase = phaseCopy(game.phase); const scene = isNight(game.phase) ? "game-scene game-scene--night" : "game-scene game-scene--day";
  return <main className={`mx-auto min-h-screen w-full max-w-[1500px] px-4 py-4 sm:px-6 lg:px-8 ${scene}`}><header className="soft-panel flex flex-wrap items-center justify-between gap-3 rounded-3xl px-4 py-3 sm:px-5"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8ba61]/12 text-[#ffe2a1]">☾</span><span><b className="display-font text-lg text-[#ffe2a1]">Làng trong rừng</b><small className="ml-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#879a88]">Ván đang chơi</small></span></Link><div className="flex items-center gap-2"><span className="hidden rounded-full border border-white/10 px-3 py-1.5 text-xs text-[#bcc9bc] sm:block">{alivePlayers.length}/{players.length} còn sống</span><button onClick={() => void refresh(session)} className="rounded-full border border-white/12 px-3 py-1.5 text-xs font-bold text-[#d3ddd2] transition hover:border-[#e8ba61]/45 hover:text-[#ffe2a1]">↻ Làm mới</button></div></header>
    <section className="mt-4 grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)_310px]">
      <aside className="order-2 space-y-4 lg:order-1"><VillagePanel players={players} selfId={privateView.playerId} /><PublicLog events={game.publicEvents} /></aside>
      <section className="order-1 min-w-0 lg:order-2"><div className="panel overflow-hidden rounded-[2rem]"><div className="relative border-b border-white/10 px-6 py-7 sm:px-9"><div className="absolute right-0 top-0 h-32 w-32 rounded-full bg-[#e8ba61]/10 blur-3xl" /><div className="relative flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e8ba61]">{phase.eyebrow}{game.phase !== "LOBBY" && game.phase !== "FINISHED" ? ` · Đêm ${game.night}` : ""}</p><h1 className="display-font mt-2 text-3xl font-bold text-[#f8f2e5] sm:text-4xl">{phase.title}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#b6c5b6]">{phase.note}</p></div><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border border-[#e8ba61]/25 bg-[#e8ba61]/10 text-2xl text-[#ffe2a1]">{phase.icon}</span></div></div>
        <div className="px-5 py-6 sm:px-8 sm:py-7">{game.phase === "LOBBY" ? <LobbyPanel playerCount={players.length} roles={roleSlots} isHost={session.isHost} disabled={acting} saved={configurationSaved} onChange={setConfiguredRoles} onSave={() => saveRoleConfiguration(roleSlots)} onStart={start} /> : <><RoleCard role={privateView.role} faction={privateView.faction} alive={self?.alive ?? false} /><LoverNotice lover={privateView.lover} />{privateView.notifications.length > 0 && <div className="mt-4 space-y-2">{privateView.notifications.map((note, index) => <p key={`${note}-${index}`} className="rounded-2xl border border-[#e8ba61]/20 bg-[#e8ba61]/8 px-4 py-3 text-sm text-[#ffe2a1]">✦ {note}</p>)}</div>}{game.phase === "DAY_EXECUTION" && self?.id === game.day.scaffoldedId && <p className="mt-4 rounded-2xl border border-[#e8ba61]/22 bg-[#e8ba61]/8 px-4 py-3 text-sm text-[#ffe2a1]">Bạn đang ở trên giàn nên không tham gia biểu quyết.</p>}{canAct && privateView.actionPhase && <ActionPanel phase={privateView.actionPhase} role={privateView.role} players={alivePlayers} actorId={privateView.playerId} targetId={targetId} secondTargetId={secondTargetId} setTargetId={setTargetId} setSecondTargetId={setSecondTargetId} disabled={acting} isHost={session.isHost} guardLastTargetId={privateView.guardLastTargetId} potions={privateView.potions} wolfTarget={personName(players, privateView.wolfBiteTarget)} wolfPack={privateView.wolfPack} wolfVotes={privateView.wolfVotes} nominationVoteTargetId={privateView.nominationVoteTargetId} nominationVoteSubmitted={privateView.nominationVoteSubmitted} executionVote={privateView.executionVote} scaffoldedName={personName(players, game.day.scaffoldedId)} onSubmit={submit} />}{game.phase === "FINISHED" && <><Winners factions={game.winners ?? []} winnerPlayerIds={game.winnerPlayerIds} players={game.finalRoles ?? []} /><FinalRoles roles={game.finalRoles ?? []} /></>}</>}</div></div>
      </section>
      <aside className="order-3 space-y-4"><PrivatePanels privateView={privateView} players={players} /><RoomCode gameId={gameId} /></aside>
    </section>{error && <p role="alert" className="fixed bottom-5 left-1/2 z-30 w-[min(92vw,38rem)] -translate-x-1/2 rounded-2xl border border-red-300/30 bg-red-950/95 px-5 py-4 text-sm text-red-100 shadow-2xl">{error}</p>}</main>;
}

function FullscreenMessage({ label, detail }: { label: string; detail?: string }) { return <main className="grid min-h-screen place-items-center px-6 text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-[#e8ba61]/30 bg-[#e8ba61]/10 text-2xl text-[#ffe2a1]">☾</span><h1 className="display-font mt-5 text-3xl font-bold">{label}</h1>{detail && <p className="mt-3 text-[#a9b6a9]">{detail}</p>}{detail && <Link href="/" className="mt-6 inline-block rounded-2xl bg-[#e8ba61] px-5 py-3 font-bold text-[#17271d]">Về trang chủ</Link>}</div></main>; }
function VillagePanel({ players, selfId }: { players: Player[]; selfId: string }) { return <div className="soft-panel rounded-3xl p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8ba61]">Ngôi làng</p><span className="rounded-full bg-white/5 px-2 py-1 text-[11px] text-[#a9b6a9]">{players.filter((p) => p.alive).length} còn sống</span></div><div className="mt-3 space-y-1.5">{players.map((player, index) => <div key={player.id} className={`flex items-center gap-3 rounded-2xl px-3 py-2.5 ${player.id === selfId ? "bg-[#e8ba61]/12 text-[#fff0c7]" : "bg-white/[.035]"}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${player.alive ? "bg-emerald-300/12 text-emerald-100" : "bg-red-400/10 text-red-200"}`}>{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-semibold">{player.name}{player.id === selfId && <small className="ml-1 text-[10px] text-[#e8ba61]">(bạn)</small>}</span><span className={`text-[10px] font-bold uppercase tracking-wide ${player.alive ? "text-emerald-300" : "text-red-300"}`}>{player.alive ? "Sống" : "Loại"}</span></div>)}</div></div>; }
function PublicLog({ events }: { events: string[] }) { return <div className="soft-panel rounded-3xl p-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8ba61]">Nhật ký chung</p><div className="mt-3 max-h-52 space-y-3 overflow-y-auto pr-1">{events.length ? [...events].reverse().map((event, index) => <p key={`${event}-${index}`} className="border-l border-[#e8ba61]/30 pl-3 text-sm leading-6 text-[#bcc9bc]">{event}</p>) : <p className="text-sm text-[#839384]">Chưa có sự kiện nào.</p>}</div></div>; }
function RoleCard({ role, faction, alive }: { role?: Role; faction?: string; alive: boolean }) { if (!role) return null; return <div className={`gold-ring rounded-3xl border p-5 ${roleTone[role]}`}><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-black/15 text-3xl">{roleIcon[role]}</span><div><p className="text-xs font-bold uppercase tracking-[.15em] opacity-70">Vai trò của bạn</p><h2 className="display-font mt-1 text-3xl font-bold">{roleName[role]}</h2><p className="mt-1 text-sm opacity-85">{faction ? factionName[faction] ?? faction : "Đang chờ xác định phe"} {!alive && "· Bạn đã bị loại"}</p></div></div></div>; }
function LoverNotice({ lover }: { lover?: GameView["private"]["lover"] }) { if (!lover) return null; return <div className="mt-4 rounded-3xl border border-pink-200/20 bg-pink-400/[.08] p-4 text-pink-50"><p className="text-xs font-bold uppercase tracking-[.15em] text-pink-200">Sợi dây tình nhân</p><p className="display-font mt-1 text-xl font-bold">♡ {lover.name}</p><p className="mt-1 text-sm text-pink-100/75">{lover.role && roleName[lover.role]} · {lover.faction && (factionName[lover.faction] ?? lover.faction)} · {lover.alive ? "Còn sống" : "Đã bị loại"}</p></div>; }
function RoomCode({ gameId }: { gameId: string }) { return <div className="soft-panel rounded-3xl p-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8ba61]">Mã phòng</p><code className="mt-3 block overflow-hidden text-ellipsis whitespace-nowrap rounded-xl bg-black/20 px-3 py-2.5 text-xs text-[#c8d4c7]">{gameId}</code></div>; }
function PrivatePanels({ privateView, players }: { privateView: GameView["private"]; players: Player[] }) { const name = (id: string) => personName(players, id); return <div className="space-y-4">{privateView.seerHistory && <HistoryPanel title="Sổ soi" icon="◉" empty="Chưa có kết quả soi." entries={privateView.seerHistory.map((item) => `Đêm ${item.night} · ${name(item.targetId)} · ${item.result === "WOLF" ? "Sói" : "Không phải Sói"}`)} />}{privateView.guardHistory && <HistoryPanel title="Sổ bảo vệ" icon="◈" empty="Chưa bảo vệ ai." entries={privateView.guardHistory.map((item) => `Đêm ${item.night} · ${name(item.targetId)}`)} />}{privateView.wolfPack && <div className="rounded-3xl border border-red-200/15 bg-red-950/20 p-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-red-200">Bầy Sói</p><div className="mt-3 space-y-2">{privateView.wolfPack.map((wolf) => <p key={wolf.id} className="rounded-xl bg-red-100/5 px-3 py-2 text-sm text-red-50">☾ {wolf.name}</p>)}</div></div>}</div>; }
function HistoryPanel({ title, icon, empty, entries }: { title: string; icon: string; empty: string; entries: string[] }) { return <div className="soft-panel rounded-3xl p-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8ba61]">{icon} {title}</p><div className="mt-3 space-y-2">{entries.length ? entries.map((entry) => <p key={entry} className="text-sm text-[#cbd7ca]">{entry}</p>) : <p className="text-sm text-[#839384]">{empty}</p>}</div></div>; }
function LobbyPanel({ playerCount, roles, isHost, disabled, saved, onChange, onSave, onStart }: { playerCount: number; roles: Role[]; isHost: boolean; disabled: boolean; saved: boolean; onChange: (roles: Role[]) => void; onSave: () => void; onStart: () => void }) { const count = (role: Role) => roles.filter((item) => item === role).length; const adjust = (role: Role, delta: number) => { if (delta < 0 && count(role)) onChange(roles.filter((item, index) => item !== role || index !== roles.lastIndexOf(role))); if (delta > 0 && roles.length < playerCount) onChange([...roles, role]); else if (delta > 0 && role !== "VILLAGER" && count("VILLAGER")) { const index = roles.lastIndexOf("VILLAGER"); onChange(roles.map((item, itemIndex) => itemIndex === index ? role : item)); } }; if (!isHost) return <div className="rounded-3xl border border-[#e8ba61]/20 bg-[#e8ba61]/7 p-6"><p className="display-font text-2xl font-bold text-[#ffe2a1]">{playerCount} người đã vào làng</p><p className="mt-2 text-sm leading-6 text-[#b7c5b7]">Chờ chủ phòng cấu hình các vai trò và bắt đầu ván.</p></div>; return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="display-font text-2xl font-bold text-[#f8f2e5]">Chuẩn bị ván chơi</p><p className="mt-1 text-sm text-[#b7c5b7]">Chọn thành phần role. Server sẽ xáo ngẫu nhiên trước khi chia.</p></div><p className={`rounded-full px-3 py-1.5 text-sm font-bold ${roles.length === playerCount ? "bg-emerald-400/12 text-emerald-200" : "bg-amber-400/12 text-amber-100"}`}>{roles.length}/{playerCount} role</p></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{ROLES.map((role) => <div key={role} className={`flex items-center justify-between rounded-2xl border px-3 py-3 ${roleTone[role]}`}><span className="flex items-center gap-2 text-sm font-bold"><i className="text-lg not-italic">{roleIcon[role]}</i>{roleName[role]}</span><div className="flex items-center gap-3"><button type="button" onClick={() => adjust(role, -1)} disabled={disabled || !count(role)} className="grid h-7 w-7 place-items-center rounded-lg border border-white/20 disabled:opacity-30">−</button><b>{count(role)}</b><button type="button" onClick={() => adjust(role, 1)} disabled={disabled || (roles.length >= playerCount && (role === "VILLAGER" || !count("VILLAGER")))} className="grid h-7 w-7 place-items-center rounded-lg border border-white/20 disabled:opacity-30">+</button></div></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={disabled || roles.length !== playerCount} onClick={onSave} className="rounded-2xl border border-[#e8ba61]/45 px-4 py-3 font-bold text-[#ffe2a1] disabled:opacity-35">Lưu cấu hình</button><button disabled={disabled || !saved} onClick={onStart} className="rounded-2xl bg-[#e8ba61] px-4 py-3 font-bold text-[#132419] disabled:opacity-35">Bắt đầu ván →</button></div>{!saved && <p className="mt-3 text-xs text-[#e8ba61]">Lưu cấu hình trước khi bắt đầu.</p>}</div>; }
function TargetGrid({ players, selectedId, onSelect, disabled, excludeIds = [] }: { players: Player[]; selectedId: string; onSelect: (id: string) => void; disabled: boolean; excludeIds?: string[] }) { return <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{players.filter((player) => !excludeIds.includes(player.id)).map((player) => <button key={player.id} type="button" disabled={disabled} onClick={() => onSelect(player.id)} className={`rounded-2xl border px-3 py-3 text-left text-sm font-bold transition disabled:opacity-45 ${selectedId === player.id ? "border-[#e8ba61] bg-[#e8ba61]/15 text-[#ffe2a1]" : "border-white/10 bg-white/[.035] text-[#dce6da] hover:border-white/25"}`}><span className="block truncate">{player.name}</span><small className="mt-1 block text-[10px] font-medium uppercase tracking-wide opacity-60">{selectedId === player.id ? "Đã chọn" : "Chọn"}</small></button>)}</div>; }
function CupidPairPicker({ players, firstId, secondId, onFirstChange, onSecondChange, disabled }: { players: Player[]; firstId: string; secondId: string; onFirstChange: (id: string) => void; onSecondChange: (id: string) => void; disabled: boolean }) {
  const first = players.find((player) => player.id === firstId); const second = players.find((player) => player.id === secondId); const selectedCount = Number(Boolean(firstId)) + Number(Boolean(secondId));
  const choose = (id: string) => { if (id === firstId) { onFirstChange(secondId); onSecondChange(""); return; } if (id === secondId) { onSecondChange(""); return; } if (!firstId) { onFirstChange(id); return; } if (!secondId) onSecondChange(id); };
  const removeFirst = () => { onFirstChange(secondId); onSecondChange(""); }; const removeSecond = () => onSecondChange("");
  return <div className="mt-5"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 rounded-3xl border border-pink-200/20 bg-pink-400/[.07] p-3 text-center sm:p-4"><CupidSlot label="Người thứ nhất" player={first} onRemove={removeFirst} disabled={disabled} /><span aria-hidden="true" className="text-2xl text-pink-200">♡</span><CupidSlot label="Người thứ hai" player={second} onRemove={removeSecond} disabled={disabled} /></div><div className="mt-5 flex items-center justify-between gap-3"><p className="text-sm font-semibold text-[#dce6da]">Chọn người chơi</p><span className="rounded-full border border-pink-200/20 bg-pink-300/10 px-2.5 py-1 text-xs font-bold text-pink-100">{selectedCount}/2 đã chọn</span></div><p className="mt-1 text-xs leading-5 text-[#9fb09f]">Bấm một người để chọn. Bấm lại người đã chọn để bỏ chọn.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{players.map((player) => { const position = player.id === firstId ? 1 : player.id === secondId ? 2 : 0; const locked = selectedCount === 2 && position === 0; return <button key={player.id} type="button" aria-pressed={Boolean(position)} disabled={disabled || locked} onClick={() => choose(player.id)} className={`relative rounded-2xl border px-3 py-3 text-left text-sm font-bold transition disabled:cursor-not-allowed ${position ? "border-pink-200/70 bg-pink-400/15 text-pink-50" : "border-white/10 bg-white/[.035] text-[#dce6da] hover:border-white/25"} ${locked ? "opacity-40" : ""}`}><span className="block truncate">{player.name}</span><small className="mt-1 block text-[10px] font-medium uppercase tracking-wide opacity-70">{position ? `Đã chọn · ${position}` : locked ? "Đủ hai người" : "Chọn"}</small>{position > 0 && <span className="absolute right-2 top-2 grid h-5 w-5 place-items-center rounded-full bg-pink-100 text-[11px] text-[#54243b]">✓</span>}</button>; })}</div>{selectedCount === 2 && <p className="mt-3 rounded-2xl border border-pink-200/15 bg-pink-400/[.06] px-3 py-2.5 text-xs text-pink-100">Đã đủ hai người. Bỏ chọn một người nếu bạn muốn thay đổi.</p>}</div>;
}
function CupidSlot({ label, player, onRemove, disabled }: { label: string; player?: Player; onRemove: () => void; disabled: boolean }) { return <div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-pink-100/60">{label}</p>{player ? <div className="mt-1 flex items-center justify-center gap-1.5"><b className="truncate text-sm text-pink-50">{player.name}</b><button type="button" aria-label={`Bỏ chọn ${player.name}`} disabled={disabled} onClick={onRemove} className="grid h-5 w-5 shrink-0 place-items-center rounded-full border border-pink-100/30 text-xs text-pink-100 hover:bg-pink-100/10 disabled:opacity-40">×</button></div> : <p className="mt-1 truncate text-sm text-pink-100/45">Chưa chọn</p>}</div>; }
function ConfirmButton({ label, disabled, onClick, muted = false }: { label: string; disabled: boolean; onClick: () => void; muted?: boolean }) { return <button disabled={disabled} onClick={onClick} className={`mt-4 w-full rounded-2xl px-4 py-3.5 text-sm font-bold transition disabled:opacity-40 ${muted ? "border border-white/15 text-[#d8e1d7] hover:bg-white/5" : "bg-[#e8ba61] text-[#122218] hover:bg-[#ffe2a1]"}`}>{label}</button>; }
function ActionPanel({ phase, role, players, actorId, targetId, secondTargetId, setTargetId, setSecondTargetId, disabled, isHost, guardLastTargetId, potions, wolfTarget, wolfPack, wolfVotes, nominationVoteTargetId, nominationVoteSubmitted, executionVote, scaffoldedName, onSubmit }: { phase: string; role?: Role; players: Player[]; actorId: string; targetId: string; secondTargetId: string; setTargetId: (id: string) => void; setSecondTargetId: (id: string) => void; disabled: boolean; isHost: boolean; guardLastTargetId?: string; potions?: { heal: boolean; poison: boolean }; wolfTarget: string; wolfPack?: Array<{ id: string; name: string }>; wolfVotes?: Record<string, string>; nominationVoteTargetId?: string | null; nominationVoteSubmitted?: boolean; executionVote?: boolean | null; scaffoldedName: string; onSubmit: Submit }) {
  const shell = (eyebrow: string, title: string, body: React.ReactNode) => <div className="mt-6 rounded-3xl border border-[#e8ba61]/18 bg-black/15 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8ba61]">{eyebrow}</p><h2 className="display-font mt-1 text-2xl font-bold">{title}</h2>{body}</div>;
  const choose = (eyebrow: string, title: string, action: GameActionType, options: Player[], confirm = "Xác nhận lựa chọn") => shell(eyebrow, title, <><TargetGrid players={options} selectedId={targetId} onSelect={setTargetId} disabled={disabled} /><ConfirmButton label={targetId ? `${confirm}: ${personName(players, targetId)}` : confirm} disabled={disabled || !targetId} onClick={() => void onSubmit(action, { targetId })} /></>);
  if (phase === "NIGHT_CUPID" && role === "CUPID") { const firstName = personName(players, targetId); const secondName = personName(players, secondTargetId); return shell("Lượt của bạn", "Ghép đôi tình nhân", <><p className="mt-2 text-sm leading-6 text-[#b7c5b7]">Chọn hai người để buộc sợi dây tình yêu. Bạn có thể chọn chính mình; vai trò và phe của họ vẫn được giữ kín.</p><CupidPairPicker players={players} firstId={targetId} secondId={secondTargetId} onFirstChange={setTargetId} onSecondChange={setSecondTargetId} disabled={disabled} /><ConfirmButton label={targetId && secondTargetId ? `Ghép ${firstName} ♥ ${secondName}` : "Chọn đủ hai người để ghép đôi"} disabled={disabled || !targetId || !secondTargetId} onClick={() => void onSubmit("PAIR_LOVERS", { targetIds: [targetId, secondTargetId] })} /></>); }
  if (phase === "NIGHT_GUARD" && role === "GUARD") return choose("Lượt của bạn", "Bảo vệ một người", "PROTECT", players.filter((player) => player.id !== guardLastTargetId), "Bảo vệ");
  if (phase === "NIGHT_WOLF" && role === "WOLF") { const voted = Boolean(wolfVotes?.[actorId]); return shell("Bầy Sói", "Bỏ phiếu mục tiêu cắn", <><p className="mt-2 text-sm leading-6 text-[#b7c5b7]">Khi các Sói còn sống đã chọn, người có nhiều phiếu nhất sẽ bị cắn. Hòa phiếu được chọn ngẫu nhiên.</p><div className="mt-4 space-y-2">{wolfPack?.map((wolf) => <div key={wolf.id} className="flex items-center justify-between rounded-xl bg-red-400/7 px-3 py-2 text-sm"><span>☾ {wolf.name}</span><b className="text-red-100">{wolfVotes?.[wolf.id] ? personName(players, wolfVotes[wolf.id]) : "Đang chọn…"}</b></div>)}</div>{voted ? <p className="mt-4 rounded-2xl bg-[#e8ba61]/10 px-4 py-3 text-sm text-[#ffe2a1]">Phiếu của bạn đã được gửi. Chờ những Sói còn lại.</p> : <><TargetGrid players={players} selectedId={targetId} onSelect={setTargetId} disabled={disabled} excludeIds={wolfPack?.map((wolf) => wolf.id) ?? []} /><ConfirmButton label={targetId ? `Gửi phiếu cắn: ${personName(players, targetId)}` : "Gửi phiếu cắn"} disabled={disabled || !targetId} onClick={() => void onSubmit("VOTE_WOLF_TARGET", { targetId })} /></>}</>); }
  if (phase === "NIGHT_SEER" && role === "SEER") return choose("Lượt của bạn", "Soi một người", "INSPECT", players.filter((player) => player.id !== actorId), "Soi");
  if (phase === "NIGHT_WITCH_HEAL" && role === "WITCH") return shell("Lượt của bạn", potions?.heal ? `Mục tiêu bị cắn: ${wolfTarget}` : "Bạn đã hết bình cứu", potions?.heal ? <div className="mt-4 grid gap-2 sm:grid-cols-2"><ConfirmButton label="Dùng bình cứu" disabled={disabled} onClick={() => void onSubmit("USE_HEAL", { use: true })} /><ConfirmButton label="Không dùng bình cứu" muted disabled={disabled} onClick={() => void onSubmit("USE_HEAL", { use: false })} /></div> : <ConfirmButton label="Tiếp tục" muted disabled={disabled} onClick={() => void onSubmit("USE_HEAL", { use: false })} />);
  if (phase === "NIGHT_WITCH_POISON" && role === "WITCH") return shell("Lượt của bạn", potions?.poison ? "Bạn có muốn dùng bình giết?" : "Bạn đã hết bình giết", potions?.poison ? <><TargetGrid players={players} selectedId={targetId} onSelect={setTargetId} disabled={disabled} /><div className="grid gap-2 sm:grid-cols-2"><ConfirmButton label="Dùng bình giết" disabled={disabled || !targetId} onClick={() => void onSubmit("USE_POISON", { use: true, targetId })} /><ConfirmButton label="Không dùng" muted disabled={disabled} onClick={() => void onSubmit("USE_POISON", { use: false })} /></div></> : <ConfirmButton label="Tiếp tục" muted disabled={disabled} onClick={() => void onSubmit("USE_POISON", { use: false })} />);
  if (phase === "DAY_NOMINATION" && nominationVoteSubmitted) return shell("Đã ghi nhận", "Lựa chọn của bạn", <p className="mt-3 text-sm text-[#ffe2a1]">{nominationVoteTargetId ? <><b>{personName(players, nominationVoteTargetId)}</b> đã được bạn đề cử lên giàn.</> : "Bạn đã gửi phiếu trắng."}</p>);
  if (phase === "DAY_NOMINATION") return shell("Lượt của bạn", "Chọn người lên giàn", <><TargetGrid players={players.filter((player) => player.id !== actorId)} selectedId={targetId} onSelect={setTargetId} disabled={disabled} /><div className="grid gap-2 sm:grid-cols-2"><ConfirmButton label={targetId ? `Đề cử: ${personName(players, targetId)}` : "Chọn một người để đề cử"} disabled={disabled || !targetId} onClick={() => void onSubmit("NOMINATE", { targetId })} /><ConfirmButton label="Gửi phiếu trắng" muted disabled={disabled} onClick={() => void onSubmit("CAST_BLANK_NOMINATION")} /></div></>);
  if (phase === "DAY_DEFENSE" && isHost) return shell("Điều phối", `${scaffoldedName} đang biện hộ`, <ConfirmButton label="Kết thúc thời gian biện hộ" disabled={disabled} onClick={() => void onSubmit("END_DEFENSE")} />);
  if (phase === "DAY_EXECUTION" && executionVote !== undefined) return shell("Đã ghi nhận", "Lựa chọn của bạn", <p className="mt-3 text-sm text-[#ffe2a1]">{executionVote === null ? "Bạn đã gửi phiếu trắng." : <>Bạn đã chọn <b>{executionVote ? "treo cổ" : "không treo"}</b> {scaffoldedName}.</>}</p>);
  if (phase === "DAY_EXECUTION") return shell("Lượt của bạn", `Có treo cổ ${scaffoldedName} không?`, <div className="mt-4 grid gap-2 sm:grid-cols-3"><ConfirmButton label="Treo cổ" disabled={disabled} onClick={() => void onSubmit("VOTE_EXECUTION", { use: true })} /><ConfirmButton label="Không treo" muted disabled={disabled} onClick={() => void onSubmit("VOTE_EXECUTION", { use: false })} /><ConfirmButton label="Phiếu trắng" muted disabled={disabled} onClick={() => void onSubmit("CAST_BLANK_EXECUTION")} /></div>);
  return <div className="mt-6 rounded-3xl border border-white/10 bg-black/15 p-5 text-sm leading-6 text-[#b7c5b7]">Hãy chờ những người chơi liên quan hoàn thành lượt của họ.</div>;
}
function Winners({ factions, winnerPlayerIds, players }: { factions: string[]; winnerPlayerIds?: string[]; players: Array<{ id: string; name: string; faction?: string }> }) { const winners = winnerPlayerIds ? players.filter((player) => winnerPlayerIds.includes(player.id)) : players.filter((player) => player.faction && factions.includes(player.faction)); return <div className="mt-6 rounded-3xl border border-[#e8ba61]/45 bg-[#e8ba61]/12 p-6 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e8ba61]">Kết quả ván chơi</p><h2 className="display-font mt-2 text-3xl font-bold text-[#fff0c7]">{factions.map((faction) => factionName[faction] ?? faction).join(" · ")} chiến thắng</h2><p className="mt-4 text-sm text-[#d3ded1]">Người chiến thắng</p><p className="display-font mt-1 text-xl font-bold text-white">{winners.map((player) => player.name).join(" · ") || "Chưa có dữ liệu"}</p></div>; }
function FinalRoles({ roles }: { roles: Array<{ id: string; name: string; role?: string; faction?: string }> }) { return <div className="mt-4 rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e8ba61]">Vai trò cuối ván</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{roles.map((player) => <p key={player.id} className="rounded-xl bg-white/[.035] px-3 py-2.5 text-sm">{player.name}<span className="mx-2 text-white/25">·</span>{player.role && roleName[player.role as Role]}<span className="mx-2 text-white/25">·</span><span className="text-[#b9c8b9]">{player.faction && (factionName[player.faction] ?? player.faction)}</span></p>)}</div></div>; }
